title: The Office for Space Technology and Industry
url: ""
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#006298"
  secondary-color: "#49759a"
  media-colors:
    - title: media-color-one
      color: "#006298"
    - title: media-color-two
      color: "#49759a"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
resources_name: latest-news
description: Singapore's National Space Office
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://edb-ostIn-staging.netlify.app
prod: https://edb-ostIn-prod.netlify.app
is_government: true
shareicon: /images/isomer-logo.svg
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
